# Dependencies
markdown:         kramdown
#redcarpet
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-extlinks

# Permalinks
permalink:        pretty

# Setup
title:            'Tien-Yiao Hsu'
tagline:          'A Jekyll theme'
description:      'Personal site'
url:              https://meteorologytoday.github.io/
baseurl:          /

author:
  name:           'Tien-Yiao Hsu'
  url:            https://twitter.com/mdo
  email:          tienyiao@ucsd.edu

paginate:         1
paginate_path:   "/page:num/"
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
